GET http://localhost:3000/users HTTP/1.1

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "fullName": "Nartay Saken",
  "email": "n.saken@gmail.com",
  "walletAddress": "mkTL2EE6kLGi4vc2JzejwR6QFxYZijG49T"
}

###

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "fullName": "Andrew Kozlov",
  "email": "andrew_kozlov@mail.ru",
  "walletAddress": "mtspYcEjMJieW158UvzmJryxW9oBaLKGtm"
}

###

DELETE http://localhost:3000/users HTTP/1.1