GET http://localhost:3000/events HTTP/1.1

###

POST http://localhost:3000/nfts HTTP/1.1
content-type: application/json

# organizationName: { type: String, required: true },
#   maxGuest: { type: Number, required: true },
#   dateStart: { type: Date, required: true },
#   image: { type: String, required: true },
#   tokens: { type: [User], required: true },
#   dateDeath: { type: Date, required: true },
{
  "organizationName": "Binance France",
    "maxGuest": 80,
    "dateStart": "2022-12-20",
    "image": "https://static.wikia.nocookie.net/chainsaw-man/images/a/ac/Power_anime_design_2.png/",
    "tokens": [],
    "dateDeath": "2022-12-30"
}
###

DELETE http://localhost:3000/events HTTP/1.1

###

POST http://localhost:3000/addUser HTTP/1.1
content-type: application/json

{
  "eventId": "change_to_your_event_id",
  "userId": "change_to_your_user_id"
}